### ISSUE TITLE
[BUG] Disappear

### ISSUE THREAD

**Issue by lucawernicke** [RienBijl/Scoreboard-revision#12]
**Describe the bug**
The Menu Disappears after 1 Second

**Spigot version(please complete the following information):**
 - Spigot
 - Minecraft v1.8

**Screenshot of /plugins**
![image](https://user-images.githubusercontent.com/55715525/116070127-8449e680-a68c-11eb-8e1f-2d8f40e6896b.png)

**Configuration file**
```
#  ____  ____  ____  ____  _____ ____  ____  ____  ____  ____
# / ___\/   _\/  _ \/  __\/  __//  _ \/  _ \/  _ \/  __\/  _ \
# |    \|  /  | / \||  \/||  \  | | //| / \|| / \||  \/|| | \|
# \___ ||  \_ | \_/||    /|  /_ | |_\\| \_/|| |-|||    /| |_/|
# \____/\____/\____/\_/\_\\____\\____/\____/\_/ \|\_/\_\\____/
#
# Scoreboard-r by Rien Bijl
# rep: github : RienBijl/Scoreboard-revision
# v: R4 1.1 RELEASE

# Do not edit! The plugin uses this to determine if the configuration is suitable
config_version: 1

settings:
  # The driver is the Scoreboard implementation used to display the user
  # Old drivers will from now on remain supported so that switching back to
  # an older (perhaps more stable) version is easy.
  driver: SCOREBOARD_DRIVER_V1
  # Should we check updates? Caution! Disabling this is not recommended
  # you might miss awesome updates *wink*
  check-updates: true

# In what worlds should we disable scoreboard?
disabled-worlds:
  - 'non_existant_world'

board:
  title:
    interval: 3
    lines:
      - '&1> &b&lCafe Montana&1<'
  rows:
    1:
      interval: 80
      lines:
        - '&bPlayer &1&l>'
    2:
      interval: 80
      lines:
        - '%player_name%'
    3:
      interval: 80
      lines:
        - '%player_ping% &7ms ping'
    4:
      interval: 80
      lines:
        - ''
    5:
      interval: 80
      lines:
        - '&bServer &1&l>'
    6:
      interval: 80
      lines:
        - '&aLobby'
    7:
      interval: 80
      lines:
        - '%server_online%/32 &7Players'
    8:
      interval: 80
      lines:
        - ''
    9:
      interval: 80
      lines:
        - '&bRank &1&l>'
    10:
      interval: 80
      lines:
        - 'Rank soon.'
    11:
      interval: 80
      lines:
        - '&bCredits &1&l>'
    12:
      interval: 80
      lines:
        - '&a0 &eCredits'
```

**Additional context**
Can you help me there?
