### ISSUE TITLE
[BUG] Scoreboard gets disabled when user rejoins the server.

### ISSUE THREAD

**Issue by Jakubk15** [RienBijl/Scoreboard-revision#15]
Describe the bug:
When user rejoins the server, scoreboard gets disabled.

1. Have scoreboard enabled on your server.
2. Leave the server.
3. Join server again.
4. Scoreboard gets disabled.

Expected behavior:
Scoreboard is still enabled.

**Screenshots**

**Spigot version(please complete the following information):**
- Purpur 1.16.5, build 1060
- Also happens on Paper 1.16.5, (I forgot build number)

Screenshot of /plugins:
![Zrzut ekranu 2021-05-4 o 13 14 29](https://user-images.githubusercontent.com/77227023/116995787-cac9c180-acda-11eb-83e6-59e9999acd7d.png)
![Zrzut ekranu 2021-05-4 o 13 15 05](https://user-images.githubusercontent.com/77227023/116995800-ce5d4880-acda-11eb-8f3e-60091a85bfbf.png)

**Configuration file**
```
#  ____  ____  ____  ____  _____ ____  ____  ____  ____  ____
# / ___\/   _\/  _ \/  __\/  __//  _ \/  _ \/  _ \/  __\/  _ \
# |    \|  /  | / \||  \/||  \  | | //| / \|| / \||  \/|| | \|
# \___ ||  \_ | \_/||    /|  /_ | |_\\| \_/|| |-|||    /| |_/|
# \____/\____/\____/\_/\_\\____\\____/\____/\_/ \|\_/\_\\____/
#
# Scoreboard-r by Rien Bijl
# rep: github : RienBijl/Scoreboard-revision
# v: R4 1.1 RELEASE

# Do not edit! The plugin uses this to determine if the configuration is suitable
config_version: 1

settings:
  # The driver is the Scoreboard implementation used to display the user
  # Old drivers will from now on remain supported so that switching back to
  # an older (perhaps more stable) version is easy.
  driver: SCOREBOARD_DRIVER_V1
  # Should we check updates? Caution! Disabling this is not recommended
  # you might miss awesome updates *wink*
  check-updates: true

# In what worlds should we disable scoreboard?
disabled-worlds:
  - 'non_existant_world'

board:
  title:
    interval: 0
    lines:
      - 'MY-SERVERNAME-HERE'
  rows:
    1:
      interval: 20
      lines:
        - '&9-&b-------------'
        - '&b-&9-&b------------'
        - '&b--&9-&b-----------'
        - '&b---&9-&b----------'
        - '&b----&9-&b---------'
        - '&b-----&9-&b--------'
        - '&b------&9-&b-------'
        - '&b-------&9-&b------'
        - '&b--------&9-&b-----'
        - '&b---------&9-&b----'
        - '&b----------&9-&b---'
        - '&b-----------&9-&b--'
        - '&b------------&9-&b-'
        - '&b-------------&9-'
    2:
      interval: 80
      lines:
        - '&9Nick » &3%player_name%'
    3:
      interval: 80
      lines:
        - '&9Punkty » &3%funnyguilds_points%'
    4:
      interval: 80
      lines:
        - '&9Gildia » &3%funnyguilds_g-name%'
    5:
      interval: 80
      lines:
        - '&9Online » &3%server_online%'
    6:
      interval: 80
      lines:
        - '&9TPS » &3%server_tps_1%'
    7:
      interval: 80
      lines:
        - '&9Ping » &3%player_ping%'
    8:
      interval: 20
      lines:
        - '&9-&b-------------'
        - '&b-&9-&b------------'
        - '&b--&9-&b-----------'
        - '&b---&9-&b----------'
        - '&b----&9-&b---------'
        - '&b-----&9-&b--------'
        - '&b------&9-&b-------'
        - '&b-------&9-&b------'
        - '&b--------&9-&b-----'
        - '&b---------&9-&b----'
        - '&b----------&9-&b---'
        - '&b-----------&9-&b--'
        - '&b------------&9-&b-'
        - '&b-------------&9-'
    9:
      interval: 0
      lines:
        - '&eMY-DOMAIN.COM'
```
