### ISSUE TITLE
[BUG] LuckPerms HEX colors problem

### ISSUE THREAD

**Issue by CroaBeast** [RienBijl/Scoreboard-revision#16]
**Describe the bug**
HEX color doesn't parses correctly with LuckPerms placeholder.

**To Reproduce**
1. Have LuckPerms and PlaceholderAPI installed.
2. Install 3 PAPI expansions with these commands: `/papi ecloud download Player` `/papi ecloud download LuckPerms`, and reload PlaceholderAPI.
2. Set up the scoreboard like I do in my config. (The Configuration File Section), and reload the scoreboard.
3. To add a prefix for yourself with a HEX color use this command: `/lp user <your nick> meta addprefix 10 "{#FFFFFF}CoolPrefix"`
4. Reload the scoreboard if it's neccesary, and see the error.

**Expected behavior**
Like other scoreboards, it can parses hex colors with the format {#FFFFFF} in the prefix or suffix and shows the color correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/66433837/117477571-c3e1bf80-af23-11eb-826d-d772c7fbf1e8.png)

**Spigot version(please complete the following information):**
git-Purpur-1060 (MC: 1.16.5)

**Screenshot of /plugins**
![image](https://user-images.githubusercontent.com/66433837/117475765-0e623c80-af22-11eb-91c6-38cabaca17a0.png)

**Configuration file**
```
#  ____  ____  ____  ____  _____ ____  ____  ____  ____  ____
# / ___\/   _\/  _ \/  __\/  __//  _ \/  _ \/  _ \/  __\/  _ \
# |    \|  /  | / \||  \/||  \  | | //| / \|| / \||  \/|| | \|
# \___ ||  \_ | \_/||    /|  /_ | |_\\| \_/|| |-|||    /| |_/|
# \____/\____/\____/\_/\_\\____\\____/\____/\_/ \|\_/\_\\____/
#
# Scoreboard-r by Rien Bijl
# rep: github : RienBijl/Scoreboard-revision
# v: R4 1.0 RELEASE

# Do not edit! The plugin uses this to determine if the configuration is suitable
config_version: 1

settings:
  # The driver is the Scoreboard implementation used to display the user
  # Old drivers will from now on remain supported so that switching back to
  # an older (perhaps more stable) version is easy.
  driver: SCOREBOARD_DRIVER_V1
  # Should we check updates? Caution! Disabling this is not recommended
  # you might miss awesome updates *wink*
  check-updates: true

# In what worlds should we disable scoreboard?
disabled-worlds:
  - 'non_existant_world'

board:
  title:
    interval: 3
    lines:
      - ' &8[&6&lVANILLA&8] &71.16.5 '
  rows:
    1:
      interval: 5
      lines:
        - ''
    2:
      interval: 80
      lines:
        - ' {#FFFCCC}Nick: &7%player_name%'
    3:
      interval: 80
      lines:
        - ' {#FFFCCC}Rango: &7%luckperms_prefix%'
    4:
      interval: 80
      lines:
        - ''
```

**Additional context**
The other HEX color formats works as intended, as you can see in the screenshot.
