### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jokeq** [RienBijl/Scoreboard-revision#19]
**Describe the bug**
When player leaves server an error get's thrown.

**To Reproduce**
1. Have a player leave the server

**Expected behavior**
I don't think this really effects the server much, but the bug will throw an error to console. 

**Screenshots**
```
Craft Scheduler Thread - 126/WARN [Scoreboard-revision] Plugin Scoreboard-revision vR4 1.1 RELEASE generated an exception while executing task 17
24.05 10:03:59 [Server] INFO java.util.ConcurrentModificationException: null
24.05 10:03:59 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_292]
24.05 10:03:59 [Server] INFO at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_292]
24.05 10:03:59 [Server] INFO at rien.bijl.Scoreboard.r.Board.ConfigBoard.run(ConfigBoard.java:80) ~[?:?]
24.05 10:03:59 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
24.05 10:03:59 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
24.05 10:03:59 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
24.05 10:03:59 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
24.05 10:03:59 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

**Spigot version(please complete the following information):**
 - Spigot Version: `git-spigot-9639cf7-4b9bc9d (MC: 1.16.1) `
 - Minecraft Version: `1.16.1`

**Screenshot of /plugins**
Insert a screenshot of /plugins here
![image](https://user-images.githubusercontent.com/66538101/119359630-d3793c00-bc77-11eb-9391-8abdb1b4c0da.png)

**Configuration file**
```yml
#  ____  ____  ____  ____  _____ ____  ____  ____  ____  ____
# / ___\/   _\/  _ \/  __\/  __//  _ \/  _ \/  _ \/  __\/  _ \
# |    \|  /  | / \||  \/||  \  | | //| / \|| / \||  \/|| | \|
# \___ ||  \_ | \_/||    /|  /_ | |_\\| \_/|| |-|||    /| |_/|
# \____/\____/\____/\_/\_\\____\\____/\____/\_/ \|\_/\_\\____/
#
# Scoreboard-r by Rien Bijl
# rep: github : RienBijl/Scoreboard-revision
# v: R4 1.1 RELEASE

# Do not edit! The plugin uses this to determine if the configuration is suitable
config_version: 1

settings:
  # The driver is the Scoreboard implementation used to display the user
  # Old drivers will from now on remain supported so that switching back to
  # an older (perhaps more stable) version is easy.
  driver: SCOREBOARD_DRIVER_V1
  # Should we check updates? Caution! Disabling this is not recommended
  # you might miss awesome updates *wink*
  check-updates: true

# In what worlds should we disable scoreboard?
disabled-worlds:
  - 'non_existant_world'

board:
  title:
    interval: 3
    lines:
        - '&eKaif Survival'
        - '&f> &eKaif Survival &f<'
        - '&c>&f> &eKaif Survival &f<&c<'
        - '&4>&c>&f> &eKaif Survival &f<&c<&4<'
        - '&c>&f> &eKaif Survival &c<&f<'
        - '&f> &eKaif Survival &f<'
  rows:
    1:
      interval: 5
      lines:
        - '&fAccount: &e%player_name%'
    2:
      interval: 5
      lines:
        - '&fBalance: &e$%vault_eco_balance_formatted%'

    3:
      interval: 80
      lines:
        - '&fDeaths: &e%statistic_deaths%'
    4:
      interval: 80
      lines:
        - '&fBiome: &e%player_biome%'
    5:
      interval: 80
      lines:
        - '&fClaim Blocks: &e%griefprevention_remainingclaims_formatted%'
    6:
      interval: 80
      lines:
        - '&f&m━━━━━━━━━━━━━━━━━━'
    7:
      interval: 80
      lines:
        - '&fCoords:'
    8:
      interval: 80
      lines:
        - '  &fX: &e%player_x%' 
    9:
      interval: 80
      lines:
        - '  &fY: &e%player_y%'
    10:
      interval: 80
      lines:
        - '  &fZ: &e%player_z%'
    11:
      interval: 80
      lines:
        - '&f&m━━━━━━━━━━━━━━━━━━'
```

**Additional context**
Over all good plugin!
