### ISSUE TITLE
[BUG] On 1.17 this plugin is not working properly

### ISSUE THREAD

**Issue by QuanTrieuPCYT** [RienBijl/Scoreboard-revision#23]
**Describe the bug**
The plugin is spamming errors into the console and the scoreboard didn't appear, only red numbers

**To Reproduce**
Only red numbers appear. No scoreboard texts and stuffs
Also it spammed my console with these:
14:06:15
java.lang.NullPointerException: null
Craft Scheduler Thread - 31/WARN14:06:16
java.lang.NoSuchFieldException: ping
at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
at com.extendedclip.papi.expansion.player.PlayerUtil$1.cacheReflection(PlayerUtil.java:88)
at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:61)
at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:49)
at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:95)
at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:345)
at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:294)
at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156)
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69)
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97)
at rien.bijl.Scoreboard.r.Plugin.Utility.ScoreboardStrings.placeholders(ScoreboardStrings.java:56)
at rien.bijl.Scoreboard.r.Board.ConfigBoard.run(ConfigBoard.java:86)
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81)
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
[Scoreboard-revision]: Plugin Scoreboard-revision vR4 1.1 RELEASE generated an exception while executing task 25
Console14:06:16
java.lang.NullPointerException: null
Craft Scheduler Thread - 31/WARN14:06:16
at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:49)
at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:95)
at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:345)
at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:294)
at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156)
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69)
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97)
at rien.bijl.Scoreboard.r.Plugin.Utility.ScoreboardStrings.placeholders(ScoreboardStrings.java:56)
at rien.bijl.Scoreboard.r.Board.ConfigBoard.run(ConfigBoard.java:86)
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81)
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
[Scoreboard-revision]: Plugin Scoreboard-revision vR4 1.1 RELEASE generated an exception while executing task 25

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/73286927/121768240-717d6980-cb87-11eb-9ba6-ddc48e8788ed.png)

**Spigot version(please complete the following information):**
 - I use Spigot 1.17, probably gonna switch to 1.17 PaperMC as PaperMC is still working on making 1.17
 - 1.17

**Screenshot of /plugins**
![image](https://user-images.githubusercontent.com/73286927/121768283-b73a3200-cb87-11eb-93eb-c4f336b05bfc.png)
plugins still working great except scoreboard and some others. Tried installing your plugin on a fresh 1.17 spigot server still no luck. Most likely because of compatibility issues

**Configuration file**
```
#  ____  ____  ____  ____  _____ ____  ____  ____  ____  ____
# / ___\/   _\/  _ \/  __\/  __//  _ \/  _ \/  _ \/  __\/  _ \
# |    \|  /  | / \||  \/||  \  | | //| / \|| / \||  \/|| | \|
# \___ ||  \_ | \_/||    /|  /_ | |_\\| \_/|| |-|||    /| |_/|
# \____/\____/\____/\_/\_\\____\\____/\____/\_/ \|\_/\_\\____/
#
# Scoreboard-r by Rien Bijl
# rep: github : RienBijl/Scoreboard-revision
# v: R4 1.1 RELEASE

# Do not edit! The plugin uses this to determine if the configuration is suitable
config_version: 1

settings:
  # The driver is the Scoreboard implementation used to display the user
  # Old drivers will from now on remain supported so that switching back to
  # an older (perhaps more stable) version is easy.
  driver: SCOREBOARD_DRIVER_V1
  # Should we check updates? Caution! Disabling this is not recommended
  # you might miss awesome updates *wink*
  check-updates: true

# In what worlds should we disable scoreboard?
disabled-worlds:
  - 'non_existant_world'

board:
  title:
    interval: 1000
    lines:
      - '&4> &d&lThicc &a&lSMP &4<'
  rows:
    1:
      interval: 1000
      lines:
        - '&c---------------'
    2:
      interval: 1000
      lines:
        - '&c&lPlayer &4&l>'
    3:
      interval: 80
      lines:
        - '&b%player_name%'
    4:
      interval: 80
      lines:
        - '&c&lPing: &r&b%player_ping% &cms'
    5:
      interval: 80
      lines:
        - ''
    6:
      interval: 1000
      lines:
        - '&c&lServer &4&l>'
    7:
      interval: 80
      lines:
        - '&c&lCPU: %spark_cpu_system%'
    8:
      interval: 80
      lines:
        - '&c&lRAM: &r&b%server_ram_used%&c/&r&b%server_ram_total% &cMB'
    9:
      interval: 80
      lines:
        - '&c&lTPS: &r&b%server_tps_1%'
    10:
      interval: 1000
      lines:
        - ''    
    11:
      interval: 1000
      lines:
        - '&c---------------'

```

**Additional context**
Try updating the plugin by making it support 1.17
