### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bbauti** [RienBijl/Scoreboard-revision#35]
**Describe the bug**
Placeholderapi placeholders wont work

**To Reproduce**
1 - Install Plugin
2 - Put "%luckperms_prefix_element_highest_on_track_rankup%" on a scoreboard line (works on tablist)
2 - Put "%ac_an_move_0.1_1_F614FB,632EFD,144FFF_&lLaGang!%" on a scoreboard line (works on tablist)
3- The placeholders wont work

**Expected behavior**
The rank and texta ppearing in the scoreboard

**Screenshots**
![Captura de pantalla 2021-09-11 164132](https://user-images.githubusercontent.com/68351913/132959628-f1c8fe60-de55-42f4-8d81-913743e8c907.png)

**Spigot version(please complete the following information):**
 - Purpur
 - 1.17.1

**Configuration file**
```
#  ____  ____  ____  ____  _____ ____  ____  ____  ____  ____
# / ___\/   _\/  _ \/  __\/  __//  _ \/  _ \/  _ \/  __\/  _ \
# |    \|  /  | / \||  \/||  \  | | //| / \|| / \||  \/|| | \|
# \___ ||  \_ | \_/||    /|  /_ | |_\\| \_/|| |-|||    /| |_/|
# \____/\____/\____/\_/\_\\____\\____/\____/\_/ \|\_/\_\\____/
#
# Scoreboard-r by Rien Bijl
# rep: github : RienBijl/Scoreboard-revision
# v: R4 1.1 RELEASE

# Do not edit! The plugin uses this to determine if the configuration is suitable
config_version: 1

settings:
  # The driver is the Scoreboard implementation used to display the user
  # Old drivers will from now on remain supported so that switching back to
  # an older (perhaps more stable) version is easy.
  driver: SCOREBOARD_DRIVER_V1
  # Should we check updates? Caution! Disabling this is not recommended
  # you might miss awesome updates *wink*
  check-updates: true

# In what worlds should we disable scoreboard?
disabled-worlds:
  - 'non_existant_world'

board:
  title:
    interval: 3
    lines:
      - '&4> &c&lScoreboard-r &4<'
      - '&4> &c&lScoreboard &4<'
      - '&4> &c&lcoreboar &4<'
      - '&4> &c&loreboa &4<'
      - '&4> &c&leb &4<'
      - '&4> &4<'
      - '&4> &c&leb &4<'
      - '&4> &c&loreboa &4<'
      - '&4> &c&lcoreboar &4<'
      - '&4> &4&lScoreboard &4<'
      - '&4> &4&lScoreboard-r &4<'
      - '&4> &c&lScoreboard-r &c&o4 &4<'
      - '&4> &4&lScoreboard-r &4&o4 ツ &4<'
      - '&4> &c&lScoreboard-r &c&o4 ツ &4<'
      - '&4> &4&lScoreboard-r &4&o4 ツ &4<'
      - '&4> &c&lScoreboard-r &c&o4 ツ &4<'
      - '&4> &c&lScoreboard-r &c&o4 &4<'
  rows:
    1:
      interval: 5
      lines:
        - '%ac_an_move_0.1_1_F614FB,632EFD,144FFF_&lLaGang!%'
        - '&4------------------------'
    2:
      interval: 80
      lines:
        - '&cPlayer &4&l>'
    3:
      interval: 80
      lines:
        - '%player_name%'
    4:
      interval: 80
      lines:
        - '&4♡ &f&o%player_health_rounded%/%player_max_health_rounded%'
        - '%player_ping% &7ms latency'
    5:
      interval: 80
      lines:
        - ''
    6:
      interval: 80
      lines:
        - '&cServer &4&l>'
    7:
      interval: 80
      lines:
        - '%server_unique_joins% &7unique players'
        - '%server_online% &7online players'
    8:
      interval: 80
      lines:
        - '%server_ram_used%mb/%server_ram_total%mb &7ram usage'
        - '%server_tps_1% &7ticks per second'
    9:
      interval: 80
      lines:
        - '%ac_an_move_0.1_1_F614FB,632EFD,144FFF_&lLaGang!%'
    10:
      interval: 80
      lines:
        - '%luckperms_prefix_element_highest_on_track_rankup%'
    11:
      interval: 80
      lines:
        - 'A plugin by HelloitsRien'
    12:
      interval: 80
      lines:
        - 'please leave a review ツ'
    13:
      interval: 5
      lines:
        - '&c------------------------'
        - '&4------------------------'
```
