### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by siroo2137** [RienBijl/Scoreboard-revision#59]
**Describe the bug**
The scoreboard is not showing on default

**To Reproduce**
1.Install the plugin
2.Restart the server
3.Change the config
4.Run /sb reload
5.You're all set up

**Expected behavior**
A scoreboard should appear on join

**Spigot version(please complete the following information):**
 - PaperSpigot git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Configuration file**
```
#  ____  ____  ____  ____  _____ ____  ____  ____  ____  ____
# / ___\/   _\/  _ \/  __\/  __//  _ \/  _ \/  _ \/  __\/  _ \
# |    \|  /  | / \||  \/||  \  | | //| / \|| / \||  \/|| | \|
# \___ ||  \_ | \_/||    /|  /_ | |_\\| \_/|| |-|||    /| |_/|
# \____/\____/\____/\_/\_\\____\\____/\____/\_/ \|\_/\_\\____/
#
# Scoreboard-r by Rien Bijl
# rep: github : RienBijl/Scoreboard-revision
# v: R4 1.1 RELEASE

# Do not edit! The plugin uses this to determine if the configuration is suitable
config_version: 1

settings:
  # The driver is the Scoreboard implementation used to display the user
  # Old drivers will from now on remain supported so that switching back to
  # an older (perhaps more stable) version is easy.
  driver: SCOREBOARD_DRIVER_V1
  # Should we check updates? Caution! Disabling this is not recommended
  # you might miss awesome updates *wink*
  check-updates: false

# In what worlds should we disable scoreboard?
disabled-worlds:
  - 'non_existant_world'

board:
  title:
    interval: 3
    lines:
      - '&r&4&l&4x&r&f&lPvP'
      - '&r&4&l&4x&r&f&lPvP'

  rows:
    1:
      interval: 5
      lines:
        - '&7&m+----------------+'
        - '&7&m------------------'
    2:
      interval: 80
      lines:
        - ''
    3:
      interval: 80
      lines:
        - '&7» &4&lPlayer'
    4:
      interval: 80
      lines:
        - '    &7%player_name%'
    5:
      interval: 80
      lines:
        - ''
    6:
      interval: 80
      lines:
        - '&7» &4&lKills:'
    7:
      interval: 80
      lines:
        - '    &7%funnyguilds_kills% &4kills.'
    8:
      interval: 80
      lines:
        - ''
    9:
      interval: 80
      lines:
        - '&7» &4&lDeaths:'
    10:
      interval: 80
      lines:
        - '    &7%funnyguilds_deaths% &4deaths.'
    11:
      interval: 80
      lines:
        - ''
    12:
      interval: 80
      lines:
        - '&7» &4&lOnline:'
    13:
      interval: 80
      lines:
        - '    &7%server_online% &4player(s)'
    14:
      interval: 80
      lines:
        - ''
    15:
      interval: 5
      lines:
        - '&7&m+----------------+'
        - '&7&m------------------'
```
