### ISSUE TITLE
[BUG] Bug line 6 of scoreboard

### ISSUE THREAD

**Issue by Hordoss** [RienBijl/Scoreboard-revision#65]
**Describe the bug**
There is a bug that occurs for new players that they don't have line 6 of the scoreboard visible.
After 5 seconds during connection, it disappears.

**To Reproduce**
1. Just log in with a new account and wait 5 seconds.

**Expected behavior**
Line 6 had to be visible to all players

**Screenshots**
![not visible](https://user-images.githubusercontent.com/47595726/180601636-e117d34e-74f1-42b0-aa66-77ac1456ced6.PNG)
![visible](https://user-images.githubusercontent.com/47595726/180601638-0ea80c73-e2bd-4ba0-8bff-5f5a797eb70e.PNG)

**Spigot version(please complete the following information):**
 - Paper
 - 1.18.1

**Screenshot of /plugins**
![image](https://user-images.githubusercontent.com/47595726/180601666-fe65d0e4-990d-4b0b-a975-671250500874.png)

**Configuration file**
```
#  ____  ____  ____  ____  _____ ____  ____  ____  ____  ____
# / ___\/   _\/  _ \/  __\/  __//  _ \/  _ \/  _ \/  __\/  _ \
# |    \|  /  | / \||  \/||  \  | | //| / \|| / \||  \/|| | \|
# \___ ||  \_ | \_/||    /|  /_ | |_\\| \_/|| |-|||    /| |_/|
# \____/\____/\____/\_/\_\\____\\____/\____/\_/ \|\_/\_\\____/
#
# Scoreboard-r by Rien Bijl
# rep: github : RienBijl/Scoreboard-revision
# v: R4 1.1 RELEASE

# Do not edit! The plugin uses this to determine if the configuration is suitable
config_version: 1

settings:
  # The driver is the Scoreboard implementation used to display the user
  # Old drivers will from now on remain supported so that switching back to
  # an older (perhaps more stable) version is easy.
  driver: SCOREBOARD_DRIVER_V1
  # Should we check updates? Caution! Disabling this is not recommended
  # you might miss awesome updates *wink*
  check-updates: true

# In what worlds should we disable scoreboard?
disabled-worlds:
  - 'non_existant_world'

board:
  title:
    interval: 3
    lines:
      - '&5> &dC&5h&dronikia &5<'
      - '&5> &dCh&5r&donikia &5<'
      - '&5> &dChr&5o&dnikia &5<'
      - '&5> &dChro&5n&dikia &5<'
      - '&5> &dChron&5i&dkia &5<'
      - '&5> &dChroni&5k&dia &5<'
      - '&5> &dChronik&5i&da &5<'
      - '&5> &dChroniki&5a &5<'
      - '&5> &5C&dhronikia &5<'
  rows:
    1:
      interval: 5
      lines:
        - ' '
    2:
      interval: 5
      lines:
        - '&7» &6Grade'
    3:
      interval: 5
      lines:
        - '&7   %vault_ranks%'
    4:
      interval: 5
      lines:
        - ' '
    5:
      interval: 5
      lines:
        - '&7» &aArgent'
    6:
      interval: 5
      lines:
        - '&7   %vault_eco_balance_formatted%'
    7:
      interval: 5
      lines:
        - ' '
    8:
      interval: 5
      lines:
        - '&7» &bTemps de jeu'
    9:
      interval: 5
      lines:
        - '&7   %statistic_hours_played%h'
    10:
      interval: 5
      lines:
        - ' '
    11:
      interval: 5
      lines:
        - '&7» &cMonde'
    12:
      interval: 5
      lines:
        - '&7   %player_world%'
```
